version: '3'

services:
  rabbitmq1:
    deploy:
      placement:
        constraints:
          - "node.labels.org.hobbit.name==worker1"
    image: rabbitmq:3-management
    hostname: rabbitmq1
    networks:
      - hobbit-core
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}

  rabbitmq2:
    deploy:
      placement:
        constraints:
          - "node.labels.org.hobbit.name==worker2"
    image: rabbitmq:3-management
    hostname: rabbitmq2
    networks:
      - hobbit-core
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbitmq3:
    deploy:
      placement:
        constraints:
          - "node.labels.org.hobbit.name==worker3"
    image: rabbitmq:3-management
    hostname: rabbitmq3
    networks:
      - hobbit-core
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    
  rabbit:
    image: haproxy:1.8-alpine
    hostname: rabbit
    networks:
      - hobbit
      - hobbit-core
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    command: /bin/sh -c "/sbin/syslogd -O /dev/stdout && haproxy -f /usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - 15672:15672
      - 5672:5672

networks:
  hobbit:
    external:
      name: hobbit
  hobbit-core:
    external:
      name: hobbit-core
